id: AB0B4CDE4
base_file: fEE1A.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.680538
  last_modified_at: 2022-06-17 12:59:45.680541
