id: AB0B4CDE4
base_file: f3F16.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.606433
  last_modified_at: 2022-06-17 12:59:45.606435
