id: AB0B4CDE4
base_file: f80C8.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.623483
  last_modified_at: 2022-06-17 12:59:45.623486
