id: AB0B4CDE4
base_file: f9A9D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.626221
  last_modified_at: 2022-06-17 12:59:45.626224
