id: AB0B4CDE4
base_file: f5B78.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.616876
  last_modified_at: 2022-06-17 12:59:45.616878
