id: AB0B4CDE4
base_file: f9CAC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.628842
  last_modified_at: 2022-06-17 12:59:45.628845
