id: AB0B4CDE4
base_file: f09E3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.597027
  last_modified_at: 2022-06-17 12:59:45.597036
