id: AB0B4CDE4
base_file: f32E1.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.602889
  last_modified_at: 2022-06-17 12:59:45.602892
