id: AB0B4CDE4
base_file: fD9D4.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.634295
  last_modified_at: 2022-06-17 12:59:45.634297
