id: AB0B4CDE4
base_file: f33AA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.604282
  last_modified_at: 2022-06-17 12:59:45.604285
