id: AB0B4CDE4
base_file: fF121.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.681907
  last_modified_at: 2022-06-17 12:59:45.681910
