id: AB0B4CDE4
base_file: f5A74.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:59:45.611854
  last_modified_at: 2022-06-17 12:59:45.611857
